spring:
  application:
    name: eleven-api
  jpa:
    open-in-view: false
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:test}
  flyway:
    enabled: false
  
  mail:
    host: ${EMAIL_HOST:smtp.titan.email}
    port: ${EMAIL_PORT:465}
    username: ${USER_NAME:contato@toponesystem.com.br}
    password: Topone147258#
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
    debug: true
    
security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}
    duration-refresh: ${JWT_DURATION_REFRESH:86400}
cors:
  origins: ${CORS_ORIGINS:http://localhost:3000,http://localhost:5173}

email:
  password-recover:
    token:
      minutes: ${PASSWORD_RECOVER_TOKEN_MINUTES:30}
    uri: ${PASSWORD_RECOVER_URI:http://localhost:3000/recover-password/}